// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkr0c3wE6-eo0YeH9LK-v5gnd5wu1Pvuo',
    appId: '1:666284506474:web:6c6a06025cd21ab0617913',
    messagingSenderId: '666284506474',
    projectId: 'fruit-market-9ce8a',
    authDomain: 'fruit-market-9ce8a.firebaseapp.com',
    storageBucket: 'fruit-market-9ce8a.appspot.com',
    measurementId: 'G-3EDRHPD2DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqchzPx_Voi8Eu7BMY2GJpCIk2X9-ex3s',
    appId: '1:666284506474:android:de27fa5cd84f01cc617913',
    messagingSenderId: '666284506474',
    projectId: 'fruit-market-9ce8a',
    storageBucket: 'fruit-market-9ce8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvkPvjVhgjUiAXZ3Y2pYK0lO_MLgDtLwY',
    appId: '1:666284506474:ios:46fe9b4dab97cd1f617913',
    messagingSenderId: '666284506474',
    projectId: 'fruit-market-9ce8a',
    storageBucket: 'fruit-market-9ce8a.appspot.com',
    iosClientId:
        '666284506474-4ds362udd89cdqrhetd7nvqbguua4hb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruit_market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvkPvjVhgjUiAXZ3Y2pYK0lO_MLgDtLwY',
    appId: '1:666284506474:ios:46fe9b4dab97cd1f617913',
    messagingSenderId: '666284506474',
    projectId: 'fruit-market-9ce8a',
    storageBucket: 'fruit-market-9ce8a.appspot.com',
    iosClientId:
        '666284506474-4ds362udd89cdqrhetd7nvqbguua4hb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruit_market',
  );
}
